version: "3.3"
services:
  backend:
    build: ./
    image: backend:image
    container_name: backend-container
    ports:
      - '8000:8000'
  frontend:
    build:
      context: ./
      dockerfile: ./Frontend/Dockerfile
    image: frontend:image
    container_name: frontend-container
    ports: 
      - "8080:8080"
    depends_on:
      - "backend"
